import React from "react";
import type { Metadata } from "next";
import Table from "../components/keydata/Table";
import TeamRadio from "../components/keydata/TeamRadio";

export const metadata: Metadata = {
  title: "KeyData",
  description: "Generated by create next app",
};

const KeyDataPage = () => {
  return (
    <>
      <div>
        <div>
          <h1 className="text-center text-xl mt-5">เค้กตามใบสั่งจอง</h1>
          <TeamRadio/>
        </div>
        <div className="mt-2">

        <Table />
        </div>
      </div>
    </>
  );
};

export default KeyDataPage;
